services:
 db:
   image: mongo:latest
   ports:
     - 27017:27017
   volumes:
     - mongo:/data/db
   environment:
     MONGO_INITDB_ROOT_USERNAME: root
     MONGO_INITDB_ROOT_PASSWORD: password123!

volumes:
  mongo: