services:
  mssql:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 1434:1433
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: password123!
    healthcheck:
      test: /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P $$MSSQL_SA_PASSWORD -C -Q 'SELECT 1'
      interval: 5s
      start_interval: 1s
      timeout: 2s
      retries: 5
      start_period: 30s
    volumes:
      - mssql22:/var/opt/mssql

volumes:
  mssql22: