services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5433:5432
    healthcheck:
      test: [ "CMD","pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    profiles: [dev]
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=duongtruong.nguyenky@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=postgres
    ports:
      - 5050:80
    volumes:
      - pgadmin:/var/lib/pgadmin

  adminer:
    profiles: [dev]
    image: adminer:latest
    restart: always
    ports:
      - 8080:8080

volumes:
  postgres: