services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5433:5432
    healthcheck:
      test: [ "CMD","pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres: